name: expenses_app
description: "ZenFi - Aplicación de gestión de gastos personales"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  get_it: ^8.0.3
  go_router: ^15.2.4
  google_fonts: ^6.2.1
  intl: ^0.20.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  provider: ^6.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

# Agrega esta sección al final del archivo
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # Requerido para íconos adaptativos en Android